language: python
python:
  - "2.7"
before_install:
  - sudo apt-get install g++
# command to install dependencies
install:
  - pip install --upgrade pip setuptools wheel
  - pip install -r requirements.txt --only-binary=numpy,scipy
  - pip install opencv-python
  - python setup.py build_ext --inplace
# specify branches to test
branches:
  only:
    - develop
    - master
# command to run tests
script: pytest
